language: php
php:
  - 7.1
  - 7.2
  - 7.3
before_install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && (cd && source ~/.nvm/nvm.sh) && nvm install
  - nvm use
  - npm install -g gulp@3.9.1
install:
  - php composer.phar install
  - nvm use
  - npm install
  - gulp --production
script: 
  - vendor/bin/phpunit

