language: php
php:
  - 7.2
  - 7.3
  - 7.4
before_install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && (cd && source ~/.nvm/nvm.sh) && nvm install
install:
  - php composer.phar install
  - nvm use
  - npm install
  - npm run prod
script: 
  - vendor/bin/phpunit

